version: '3'
services:
  enovoy:
    image: christmascard/envoy
    networks:
      - service
    ports:
    - "8080:8080"
    - "80:80"
  frontend:
    hostname: frontend
    image: christmascard/frontend
    networks:
      - service
    depends_on:
      - server
  server:
    hostname: server
    image: christmascard/alpine-node:8.12.0
    networks:
      - service
    volumes:
      - ./server:/app
      - ./christmascard.proto:/app/christmascard.proto
      - ./card-config.yml:/app/card-config.yml
    environment:
      PGHOST: database
      PGUSER: christmas
      PGDATABASE: christmas
      PGPASSWORD: christmas
      PGPORT: 5432
    working_dir: /app
    command: node ./
  database:
    image: postgres:11.1-alpine
    hostname: database
    networks:
      - service
    environment:
      POSTGRES_USER: christmas
      POSTGRES_PASSWORD: christmas
networks:
  service:
    external: false
    driver: bridge
