version: '3'
services:
  enovoy:
    image: christmascard/envoy
    networks:
      - service
    ports:
    - "8080:8080"
    - "80:80"
  frontend:
    hostname: frontend
    image: christmascard/alpine-node:8.12.0
    networks:
      - service
    depends_on:
      - server
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run start
  server:
    hostname: server
    image: christmascard/alpine-node:8.12.0
    networks:
      - service
    volumes:
      - ./server:/app
      - ./christmascard.proto:/app/christmascard.proto
      - ./card-config.yml:/app/card-config.yml
    working_dir: /app
    command: node ./
networks:
  service:
    external: false
    driver: bridge
